/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include <string.h>
#include <stdlib.h>

#include "DIALOG.h"
#include "MPUGrapher.h"
#include "VirtualDMP.h"
#include "MPU6050.h"
#include "KalmanFilter.h"
#include "key.h"
#include "remote.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_GRAPH_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_1 (GUI_ID_USER + 0x03)
#define ID_TEXT_0 (GUI_ID_USER + 0x04)
#define ID_GRAPH_1 (GUI_ID_USER + 0x05)


// USER START (Optionally insert additional defines)
u8 flag;
static I16 _aValue[3];
static GRAPH_DATA_Handle  _ahData[3];

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 0, 0, 650, 300, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 50, 350, 150, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 500, 350, 150, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 200, 310, 200, 40, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
void Grapher_Init(WM_MESSAGE *pMsg)
{
	WM_HWIN hItem;
	hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
  GRAPH_SetGridDistY(hItem, 25);
  GRAPH_SetGridVis(hItem, 1);
  GRAPH_SetGridFixedX(hItem, 1);
	GRAPH_SetBorder(hItem, 5, 5, 5, 20);
}

/*********************************************************************/

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int     NCode;
  int     Id;
  WM_HWIN  hItem;
	WM_HWIN  hLine;
  // USER START (Optionally insert additional variables)
  // USER END
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 20);
    FRAMEWIN_SetText(hItem, "MPU Observer");
    //
    // Initialization of 'Graph'
    //
			Grapher_Init(pMsg);
      _ahData[0] = GRAPH_DATA_YT_Create(GUI_GREEN, 1000, 0, 1000);
			_ahData[1] = GRAPH_DATA_YT_Create(GUI_BLUE, 1000, 0, 1000);
			_ahData[2] = GRAPH_DATA_YT_Create(GUI_RED, 1000, 0, 1000);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
      GRAPH_AttachData(hItem, _ahData[0]);
			hLine=GRAPH_SCALE_Create(290,GUI_TA_LEFT,GRAPH_SCALE_CF_HORIZONTAL,40);
			GRAPH_AttachScale(hItem, hLine);
			GRAPH_AttachData(hItem, _ahData[1]);
			GRAPH_AttachData(hItem, _ahData[2]);
			GRAPH_DATA_YT_SetOffY(_ahData[0],200);
			GRAPH_DATA_YT_SetOffY(_ahData[1],130);
			GRAPH_DATA_YT_SetOffY(_ahData[2],50);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "FullScreen");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "Exit");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "MPU Observer");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, 0x00FF0000);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				//hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
				hItem=GRAPH_CreateEx(0,0,800,480,WM_HBKWIN, WM_CF_SHOW, 0, GUI_ID_GRAPH1);			
				GRAPH_SetGridDistY(hItem, 25);
				GRAPH_SetGridVis(hItem, 1);
				GRAPH_SetGridFixedX(hItem, 1);
				GRAPH_SetBorder(hItem, 5, 5, 5, 20);
				_ahData[0] = GRAPH_DATA_YT_Create(GUI_GREEN, 1000, 0, 1000);
				_ahData[1] = GRAPH_DATA_YT_Create(GUI_BLUE, 1000, 0, 1000);
				_ahData[2] = GRAPH_DATA_YT_Create(GUI_RED, 1000, 0, 1000);
				GRAPH_AttachData(hItem, _ahData[0]);
				hLine=GRAPH_SCALE_Create(450,GUI_TA_LEFT,GRAPH_SCALE_CF_HORIZONTAL,40);
				GRAPH_AttachScale(hItem, hLine);
				GRAPH_AttachData(hItem, _ahData[1]);
				GRAPH_AttachData(hItem, _ahData[2]);
				GRAPH_DATA_YT_SetOffY(_ahData[0],300);
				GRAPH_DATA_YT_SetOffY(_ahData[1],200);
				GRAPH_DATA_YT_SetOffY(_ahData[2],100);
				// USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        flag=1;
				hItem = pMsg->hWin;
				GUI_EndDialog(hItem,0);
				// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
u8 remoteID;
void CreateGrapher(void)
{
	WM_HWIN hDlg;
	float Pitch,Roll,Yaw;
	short aacx,aacy,aacz;
	short gyrox,gyroy,gyroz;
	hDlg = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	MPU_Init();
	while (1) 
	{
	remoteID=Remote_Scan();
	if(remoteID==162)
	{
		__set_FAULTMASK(1);
		NVIC_SystemReset();
	}
	if(flag==1){flag=0;break;}
	MPU_Get_Accelerometer(&aacx,&aacy,&aacz);
	MPU_Get_Gyroscope(&gyrox,&gyroy,&gyroz);
	aacx=Kalman_Filter_X(aacx,gyrox);
	aacy=Kalman_Filter_Y(aacy,gyroy);
	Roll = GetRoll(aacx,aacy,aacz);
	Pitch = GetPitch(aacx,aacy,aacz);
	Yaw = GetYaw(gyroz);
	WM_GetDialogItem(hDlg, GUI_ID_GRAPH0);
  _aValue[0] = Roll;
	_aValue[1] = Pitch;
	_aValue[2] = Yaw;
  GRAPH_DATA_YT_AddValue(_ahData[0], _aValue[0]);
	GRAPH_DATA_YT_AddValue(_ahData[1], _aValue[1]);
	GRAPH_DATA_YT_AddValue(_ahData[2], _aValue[2]);
  GUI_Exec();
  }
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
